import { createAction, props } from '@ngrx/store';

/**  Autogenerated <%=classify(name)%> actions */

export const <%=camelize(name)%>Actions = {
  <%=camelize(name)%>: createAction('[<%=classify(name)%>] <%=decamelize(name)%>', props<{ payload: <%=classify(name)%>Payload }>()),
  <%=camelize(name)%>Success: createAction('[<%=classify(name)%>] <%=decamelize(name)%> SUCCESS'),
  <%=camelize(name)%>Failure: createAction(
    '[<%=classify(name)%>] <%=decamelize(name)%> FAILURE',
    props<{ error: ApiError }>(),
  ),
};
